/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./**/*.html",
    "./**/*.js",
    "../ds/src/**/*.js",
    "../ds/src/**/*.css",
  ],

  theme: {
    extend: {
      colors: {
        brand: {
          black: 'var(--color-brand-black)',
          'black-hover': 'var(--color-brand-black-hover)',
          orange: 'var(--color-brand-orange)',
          'orange-hover': 'var(--color-brand-orange-hover)',
          error: '#D32F2F',
          success: '#388E3C',
        },
        gray: {
          100: 'var(--color-gray-100)',
          200: 'var(--color-gray-200)',
          300: 'var(--color-gray-300)',
          400: 'var(--color-gray-400)',
          500: 'var(--color-gray-500)',
          600: 'var(--color-gray-600)',
          700: 'var(--color-gray-700)',
          800: 'var(--color-gray-800)',
          900: 'var(--color-gray-900)',
        },
      },
      spacing: {
        xxs: 'var(--space-xxs)',
        xs: 'var(--space-xs)',
        s: 'var(--space-s)',
        m: 'var(--space-m)',
        l: 'var(--space-l)',
        xl: 'var(--space-xl)',
        xxl: 'var(--space-xxl)',
        xxxl: 'var(--space-xxxl)',
      },
      screens: {
        xs: '0px',
        s: '375px',
        m: '768px',
        l: '1024px',
        xl: '1440px',
        xxl: '1920px',
      },
      borderRadius: {
        none: '0',
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        round: 'var(--radius-round)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        xxl: 'var(--shadow-xxl)',
        'elevation-1': 'var(--shadow-sm)',
        'elevation-2': 'var(--shadow-md)',
        'elevation-3': 'var(--shadow-lg)',
        'elevation-4': '0 24px 64px rgba(0, 0, 0, 0.16)',
      },
      fontFamily: {
        main: ['Prompt', 'sans-serif'],
      },
      fontSize: {
        h1: 'var(--fs-h1)',
        h2: 'var(--fs-h2)',
        h3: 'var(--fs-h3)',
        h4: 'var(--fs-h4)',
        body: 'var(--fs-body)',
      },
      fontWeight: {
        light: 'var(--fw-light)',
        regular: 'var(--fw-regular)',
        medium: 'var(--fw-medium)',
        bold: 'var(--fw-bold)',
      },
      lineHeight: {
        tight: 'var(--lh-tight)',
        base: 'var(--lh-base)',
      },
      opacity: {
        low: 'var(--opacity-low)',
        medium: 'var(--opacity-medium)',
        high: 'var(--opacity-high)',
      },
      zIndex: {
        below: 'var(--z-below)',
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        overlay: 'var(--z-overlay)',
        modal: 'var(--z-modal)',
        popover: 'var(--z-popover)',
        tooltip: 'var(--z-tooltip)',
        max: 'var(--z-max)',
      },
    },
  },
  plugins: [],
}
